version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: almahra_db
    environment:
      POSTGRES_DB: almahra_ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - almahra_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: almahra_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - almahra_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: almahra_backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres123@db:5432/almahra_ecommerce
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-super-secret-key-change-in-production
      - JWT_SECRET_KEY=your-jwt-secret-key-change-in-production
      - STRIPE_SECRET_KEY=sk_test_your_stripe_secret_key
      - STRIPE_PUBLISHABLE_KEY=pk_test_your_stripe_publishable_key
      - MAIL_SERVER=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USE_TLS=True
      - MAIL_USERNAME=your-email@gmail.com
      - MAIL_PASSWORD=your-app-password
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db
      - redis
    networks:
      - almahra_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  almahra_network:
    driver: bridge
